export const ActionTypes = {
    SET_STARRED_MESSAGES: 'SET_STARRED_MESSAGES',
    REMOVE_STARRED_MESSAGES: 'REMOVE_STARRED_MESSAGES',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    DELETE_CONVERSATION: 'DELETE_CONVERSATION',
    ADD_MESSAGE: 'ADD_MESSAGE',
    ADD_ATTACHMENT: 'ADD_ATTACHMENT',
};