export const ActionTypes = {
    SET_STARRED_MESSAGES: 'SET_STARRED_MESSAGES',
    REMOVE_STARRED_MESSAGES: 'REMOVE_STARRED_MESSAGES',
    REPLY_MESSAGE: 'REPLY_MESSAGE',
    DELETE_REPLY_MESSAGE: 'DELETE_REPLY_MESSAGE',
};